name: localstack-e2e
on: push
jobs:
  localstack-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Start LocalStack Pro (awslocal & tflocal)
        env:
            LOCALSTACK_AUTH_TOKEN: ${{ secrets.LOCALSTACK_AUTH_TOKEN }}
        run: |
          pip install localstack awscli-local[ver1] # Install LocalStack & awslocal
          pip install terraform-local               # Install tflocal
          docker pull localstack/localstack         # Make sure to pull the latest version of the image
          localstack start -d                       # Start LocalStack in the background

          echo "Waiting for LocalStack startup..."  # Wait 30 seconds for the LocalStack container
          localstack wait -t 30                     # to become ready before timing out
          echo "Startup complete"          
      - name: Init Terraform LocalStack Workspace
        working-directory: ./terraform
        run: |
          tflocal init
          tflocal workspace new e2e
          export TFWS=$(tflocal workspace show)
          echo $TFWS