name: localstack-e2e
on: push
jobs:
  e2e-localstack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Golang
        uses: actions/setup-go@v4
        with:
           go-version: '1.21.x'
      - uses: actions/checkout@v2
      - name: Build Sources
        working-directory: ./src
        run: |
            make build
      - name: Start LocalStack Pro (awslocal & tflocal)
        env:
            LOCALSTACK_AUTH_TOKEN: ${{ secrets.LOCALSTACK_AUTH_TOKEN }}
        run: |
          pip install localstack awscli-local[ver1] # Install LocalStack & awslocal
          pip install terraform-local               # Install tflocal
          docker pull localstack/localstack         # Make sure to pull the latest version of the image
          localstack start -d                       # Start LocalStack in the background
        
          echo "Waiting for LocalStack startup..."  # Wait 30 seconds for the LocalStack container
          localstack wait -t 30                     # to become ready before timing out
          echo "Startup complete"          
      - name: Initialize Terraform LocalStack
        env:
            LOCALSTACK_AUTH_TOKEN: ${{ secrets.LOCALSTACK_AUTH_TOKEN }}
            TF_LOG: "ERROR"                         # Only LOG errors in the CI/CD
        working-directory: ./terraform
        run: |
            # Initialize TF
            tflocal init
            # New Workspace Space
            tflocal workspace new e2e
            export TFWS=$(tflocal workspace show)
            # Force Applied
            tflocal apply -auto-approve
      - name: Run e2e Tests
        working-directory: ./terraform
        run: |
            ../e2e.sh
